<?php

namespace ContainerHVcCBbH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifier_TransportFactory_SlackService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'notifier.transport_factory.slack' shared service.
     *
     * @return \Symfony\Component\Notifier\Bridge\Slack\SlackTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Transport/AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/slack-notifier/SlackTransportFactory.php';

        return new \Symfony\Component\Notifier\Bridge\Slack\SlackTransportFactory(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['http_client'] ?? $container->load('getHttpClientService')));
    }
}
